### ISSUE TITLE
panic: runtime error: index out of range RC1

### ISSUE THREAD

**Issue by nickvth** [mesosphere/mesos_exporter#37] opened 2017-05-15 09:27 UTC
panic: runtime error: index out of range

goroutine 18 [running]:
main.func·032(0xc208106810, 0x7f8199bc13d0, 0xc20802b4a0)
	/home/fish/dev/go/src/github.com/mesosphere/mesos-exporter/master_state.go:218 +0x35c
main.(*masterCollector).Collect(0xc20801de20, 0xc2080365a0)
	/home/fish/dev/go/src/github.com/mesosphere/mesos-exporter/master_state.go:241 +0x44d
github.com/prometheus/client_golang/prometheus.func·014(0x7f8199bc1578, 0xc20801de20)
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/registry.go:416 +0x62
created by github.com/prometheus/client_golang/prometheus.(*registry).writePB
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/registry.go:417 +0x361

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc20800e4c0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800e4c0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20800e460, 0x0, 0x7f8199bc0c10, 0xc208028b48)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080381e8, 0x48170e, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2080381e8, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208036480, 0x7f8199bc2830, 0xc2080381e8, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208036480, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0x7a5aa0, 0x5, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1808 +0xba
main.main()
	/home/fish/dev/go/src/github.com/mesosphere/mesos-exporter/main.go:64 +0x7cb

goroutine 14 [runnable]:
github.com/prometheus/client_golang/prometheus.(*registry).writePB(0xc2080360c0, 0x7f8199bc2bd0, 0xc20802b810, 0x85b200, 0x0, 0x0, 0x0)
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/registry.go:428 +0x46b
github.com/prometheus/client_golang/prometheus.(*registry).ServeHTTP(0xc2080360c0, 0x7f8199bc2ae8, 0xc208038200, 0xc2080328f0)
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/registry.go:376 +0x13f
net/http.Handler.ServeHTTP·fm(0x7f8199bc2ae8, 0xc208038200, 0xc2080328f0)
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/http.go:61 +0x57
github.com/prometheus/client_golang/prometheus.func·008(0x7f8199bc29e8, 0xc20802c280, 0xc2080328f0)
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/http.go:158 +0x2fb
net/http.HandlerFunc.ServeHTTP(0xc2080648a0, 0x7f8199bc29e8, 0xc20802c280, 0xc2080328f0)
	/usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800aa80, 0x7f8199bc29e8, 0xc20802c280, 0xc2080328f0)
	/usr/lib/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208036480, 0x7f8199bc29e8, 0xc20802c280, 0xc2080328f0)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20802c000)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 15 [chan send]:
github.com/prometheus/client_golang/prometheus.computeApproximateRequestSize(0xc2080328f0, 0xc208036540, 0x146)
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/http.go:187 +0x1b9
created by github.com/prometheus/client_golang/prometheus.func·008
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/http.go:146 +0x160

goroutine 16 [runnable]:
sync.(*WaitGroup).Wait(0xc2080a4460)
	/usr/lib/go/src/sync/waitgroup.go:132 +0x169
github.com/prometheus/client_golang/prometheus.func·013()
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/registry.go:410 +0x30
created by github.com/prometheus/client_golang/prometheus.(*registry).writePB
	/home/fish/dev/go/src/github.com/prometheus/client_golang/prometheus/registry.go:412 +0x220

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc20802bce0)
	/usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:661 +0xcbc

goroutine 34 [runnable]:
net/http.(*persistConn).readLoop(0xc20802bce0)
	/usr/lib/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:660 +0xc9f

goroutine 30 [select]:
net/http.(*persistConn).writeLoop(0xc20802b970)
	/usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:661 +0xcbc

goroutine 29 [IO wait]:
net.(*pollDesc).Wait(0xc20800f090, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800f090, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20800f030, 0xc208114000, 0x1000, 0x1000, 0x0, 0x7f8199bc0c10, 0xc208029e68)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080382e8, 0xc208114000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8199bc28f0, 0xc2080382e8, 0xc20802b9c8, 0xc208114000, 0x1000, 0x1000, 0xc208030a80, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080a4a80, 0xc208114000, 0x1000, 0x1000, 0xc208010000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208037080)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208037080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20802b970)
	/usr/lib/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:660 +0xc9f

**Comment by Fra-nk** [comment] 2017-05-16 23:09
Sorry, but without more information there is little one can do to help you:

- OS? Go Version? Mesos Version?
- Can you reach the mesos endpoint(s) via `curl`?
- Mesos-exporter configuration?

**Comment by nickvth** [comment] 2017-05-17 12:57
Running on centos 7
We are using mesas-exporter RC1, downloaded from github.  
Yes we can reach the mesos endpoints 
Mesos-exporter is crashing we call /metrics endpoint
mesos version: 1.0.1

**Comment by StephanErb** [comment] 2017-05-17 16:58
Please try using the current version from master if this works better (rather than the RC).

**Comment by nickvth** [comment] 2017-05-18 06:41
Yesterday I build a docker image with the master branch, today I will test this. I will let you know the result

**Comment by nickvth** [comment] 2017-05-18 09:36
master branch is working, when is the officieel release?

**Comment by Rudd-O** [comment] 2017-07-18 12:41
We're hitting this bug.  Please do a release so we can roll forward!

**Comment by lhoss** [comment] 2017-08-25 15:50
let's release please !

**Comment by StephanErb** [comment] 2017-09-01 11:21
As the issue is already fixed on master, I am closing this issue. 

I am working on the release right now. I hope to have it done by the end of the day.

**Closed by StephanErb** 2017-09-01 11:21 UTC
